# Generated by Django 5.0.3 on 2024-07-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
